run-dev-dashboard:
	@echo "Run dashboard in local development mode..."
	uv run streamlit run dashboard_run.py

run-dev-feature-reader:
	@echo "Testing the feature reader without dashboard..."
	uv run python -m utils.feature_reader