[project]
name = "candles"
version = "0.1.0"
description = "Converts trades in candlesticks (real-time or for historic tardes)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
    "quixstreams>=3.8.1",
]
