version: "3.7"
name: data-backfill-historical
networks:
  redpanda_network:
    external: true
    name: redpanda_network
services:
  trades_ingestion:
    build:
      context: ../services/trades_ingestion
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_TOPIC=trades_historical_${RUN_ID}
      - PAIRS=["BTC/USD", "BTC/EUR", "ETH/EUR", "ETH/USD"]
      - LAST_N_DAYS=10
      - DATA_SOURCE=historical
    restart: on-failure

  candles:
    build:
      context: ../services/candles
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    environment:
      - KAFKA_BROKER_ADDRESS=redpanda:9092
      - KAFKA_INPUT_TOPIC=trades_historical_${RUN_ID}
      - KAFKA_OUTPUT_TOPIC=candles_historical_${RUN_ID}
      - KAFKA_CONSUMER_GROUP=candles_historical_${RUN_ID}
      - CANDLE_SECONDS=60
      - EMIT_INCOMPLETE_CANDLES=False
      - DATA_SOURCE=historical
    restart: on-failure

  to-feature-store:
    build:
      context: ../services/feature_store
      dockerfile: Dockerfile
    networks:
      - redpanda_network
    env_file:
      - ../services/to-feature-store/hopsworks_credentials.env
    environment:
      - KAFKA_BROKER_ADDRESS=localhost:19092
      - KAFKA_INPUT_TOPIC=candles_historical
      - KAFKA_CONSUMER_GROUP=to_feature_store_historical_consumer_group
      - FEATURE_GROUP_NAME=candles
      - FEATURE_GROUP_VERSION=1
      - FEATURE_GROUP_PRIMARY_KEYS=["pair", "candle_seconds"]
      - FEATURE_GROUP_EVENT_TIME=timestamp_ms
      - FEATURE_GROUP_MATERIALIZATION_INTERVAL_MINUTES=15
      - DATA_SOURCE=historical
    restart: on-failure
