[project]
name = "feature-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pydantic-settings>=2.6.1",
    "pydantic>=2.10.6",
    "quixstreams>=3.8.1",
    "pandas>=2.2.3",
]
